// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdOwkDsPGGlJcr8I3qothG29sTSzG9zk',
    appId: '1:908731371262:web:5fd5197edbdbd5e76f5faf',
    messagingSenderId: '908731371262',
    projectId: 'shujaa-spices',
    authDomain: 'shujaa-spices.firebaseapp.com',
    storageBucket: 'shujaa-spices.appspot.com',
    measurementId: 'G-SQSEC3BHQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpy562uJsqYZReoiHEy8m6aVoZ1uL4t5M',
    appId: '1:908731371262:android:2feda9cba2cc54d06f5faf',
    messagingSenderId: '908731371262',
    projectId: 'shujaa-spices',
    storageBucket: 'shujaa-spices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhOXmAX327i6KTpfJeIGdfs8Ce6K5HMiA',
    appId: '1:908731371262:ios:6d1b467e3c5c8c266f5faf',
    messagingSenderId: '908731371262',
    projectId: 'shujaa-spices',
    storageBucket: 'shujaa-spices.appspot.com',
    iosClientId: '908731371262-o2mvq7l8hnb60mqfetu4spc6bvjqf3df.apps.googleusercontent.com',
    iosBundleId: 'com.example.updateYro',
  );
}
